version: '2.2'
services:
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    restart: always 
  web:
    image: manohar4524/node-webapp:1.0.0
    ports: 
      - 3000
    environment:
      - MONGO_HOST=mongo
    scale: 3
    restart: always
  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
